In [1]:
import numpy as np

In [2]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
aa = a.reshape(3,3).astype(np.double)
aa

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [5]:
print(aa.shape)

(3, 3)


In [6]:
aa*3

array([[ 3.,  6.,  9.],
       [12., 15., 18.],
       [21., 24., 27.]])

In [8]:
b = np.arange(1,4)
b

array([1, 2, 3])

In [9]:
print(b.shape)

(3,)


In [11]:
b[1:-1]

array([2])

In [12]:
bb = b[np.newaxis,:]
bb

array([[1, 2, 3]])

In [13]:
bbb = b[:,np.newaxis]
bbb

array([[1],
       [2],
       [3]])

In [14]:
c = np.arange(1,5)
c

array([1, 2, 3, 4])

In [15]:
d = aa*c[:,np.newaxis,np.newaxis]
d

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[ 2.,  4.,  6.],
        [ 8., 10., 12.],
        [14., 16., 18.]],

       [[ 3.,  6.,  9.],
        [12., 15., 18.],
        [21., 24., 27.]],

       [[ 4.,  8., 12.],
        [16., 20., 24.],
        [28., 32., 36.]]])

In [22]:
(d.T+c).T

array([[[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]],

       [[ 4.,  6.,  8.],
        [10., 12., 14.],
        [16., 18., 20.]],

       [[ 6.,  9., 12.],
        [15., 18., 21.],
        [24., 27., 30.]],

       [[ 8., 12., 16.],
        [20., 24., 28.],
        [32., 36., 40.]]])